### ISSUE TITLE
Switch to another file extension

### ISSUE THREAD

**Issue by nguyenphuminh** [VLabStudio/Helium-X#1]
.hx is already used for Haxe, would it be better if you switch to another file extension ?

**Comment by VLabStudio** [comment]
Yes, that might be a good idea. Do you have an idea for a different extension name?

**Comment by nguyenphuminh** [comment]
Hmmm, I was thinking of .helx or .hlmx

**Comment by VLabStudio** [comment]
I have now changed it to .helx And thank you so much to nguyenphuminh for the input, it's much appreciated.
